language: node_js

node_js:
  - "10"

cache: yarn

install:
    - yarn

script:
    - yarn run lint
    - yarn run test
    - npx serverless package --stage dev

after_script:
    - yarn run coveralls
