service: serverless-boilerplate
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  environment: #Global Environment variables
    ${file(./config/${self:provider.stage}.yml)}

functions:
  ${file(./handlers/endpoints/index.yml)}

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}

  serverless-offline:
    host: '0.0.0.0'
    port: '4000'

plugins:
  - serverless-offline

package:
  exclude:
    - ./__test__/**
    - ./.nvmrc