service: ${self:custom.serviceName}
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  reservedConcurrency: 2
  timeout: 6
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}

  usagePlan:
    quota:
      limit: 100
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 10
      rateLimit: 5

  environment: #Global Environment variables
    ${file(./config/${self:provider.stage}.yml)}

functions:
  ${file(./handlers/endpoints/index.yml)}

custom:
  serviceName: ${opt:name, 'serverless-boilerplate'}
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}

  serverless-offline:
    host: '0.0.0.0'
    port: '4000'

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false
  exclude:
    - node_modules/**
    - '!node_modules/slugify/**'
    - ./__test__/**
    - ./.nvmrc
    - ./config/**
    - ./handlers/**
